### ISSUE TITLE
Minimize app on icon click

### ISSUE THREAD

**Issue by kajzersoze** [robint99/mate-dock-applet#80]
Did some updates and this feature doesn't work anymore ?
So, it used to be like this : on icon click opened app would restore if it was minimized and it would minimize if it was not minimized. Now it just restores on click and doesn't minimize.

**Comment by kajzersoze** [comment]
Yeah, had to downgrade to v0.74 and it's fine there.
I just don't understand why you had to remove that feature !?

**Comment by clessley** [comment]
I cannot minimize a single window on dock icon click. Using compiz, 16.10.

**Comment by kajzersoze** [comment]
Wait, without compiz that works ?
Haven't tried that, but anyway I am stuck with 0.74 because of that, I always thought author removed that feature for some reason. I tried today 0.76, it's nice but had to downgrade to 0.74 
btw I can restore the window on icon click but I can't minimize.
Anyway I'll reopen this.

**Comment by clessley** [comment]
@kajzersoze Thanks for re-opening the Issue. The multi-window restore with the full screen previews works great with compiz. Its a little strange that restore window works in this manner but not with a single window. Thanks for reopening the Issue.

**Comment by kajzersoze** [comment]
I just tried with marco instead of compiz and the problem I have is still there, so compiz has nothing to do with this, at least in my case. He removed it here I think : a3223c5e7e3e3c41e0be1d6d5fc3e4164768b418

**Comment by robint99** [comment]
After looking at the way some other docks and desktops handle this, I'm going to 'borrow' KDE's solution. - in other words, for apps which only have a single window open I'll restore the old behaviour where clicking the app icon will minimize or restore the window, but If an app has multiple windows open then the window list/window spread will appear as at present.

As for the Firefox/Compiz issue of  not being able to restore a window if a maximised window is also open, I can't reproduce this. However, I currently only have 16.10 installed in a virtual machine, so over the next day or two I'll install it on real hardware and try again...

**Comment by kajzersoze** [comment]
Awesome, that would be great, thanks !

**Comment by kajzersoze** [comment]
btw I just watched this video and apparently there is some blinking bug in 0.76, also the author of that video talks about this issue (minimize not working), so check it out :
https://www.youtube.com/watch?v=pPHdXGyv-D8

**Comment by robint99** [comment]
I've just committed a fix for the minimize problem and all is working fine now. If you want it right now you'll have to build the applet yourself, or else wait until the next release of the applet finds its way into the repos.

As for the Firefox/Compiz thing, I can't reproduce this. It just works for me everytime, no matter what window manager - marco, compton or compiz - I use, or whether or not I'm using a virtual machine or real hardware.

I had a look at the video, and there's now a comment on there that says that the blinking went away after he unpinned virtualbox and pinned it again. Unfortunately, this is another one of those annoying things that works every time for me. For me the Virtualbox icon - and that of every other app I've tried - blinks only when the app is loading and then stops. So I don't know what was going on, but will watch out for it happening in the future.

**Comment by kajzersoze** [comment]
Working great, thanks !

Firefox/Compiz is another issue and it's not belonging here, I don't have that issue either btw.

Virtualbox is also working fine and doesn't blink constantly, of course I would have to play with this new version more to see if that happens, but for now it doesn't.

**Comment by clessley** [comment]
Updated using the webupd8 ppa.

Still cannot minimize an open program by clicking the icon in the dock; compiz, marco gpu, doesn't matter. Restore works fine as long as not maximized window (doesn't matter what program all same behavior if maximized). I see the blinking error on the video above.

I'm using an Nvidia GT218 GeForce 8400 GS Rev. 3 with the X.Org server Noveau display (not the closed-source driver v340.101 from Nvidia).

What sort of logs do you need from me to confirm the issue?

**Comment by robint99** [comment]
I haven't released a new version of the applet (e.g. V0.77) so the webupd8 ppa won't have the fix. If you want to get hold of it you'll have to compile the applet from source. Instructions are on the main repo page [here](https://github.com/robint99/mate-dock-applet#other-distributions). Simply uninstall the version of the applet from the ppa and follow the instructions, making sure you compile for the gtk2/gtk3 as appropriate for your version of MATE. 

Any problems with this, just let me know...

**Comment by clessley** [comment]
This has fixed my full screen restore issue, from the main read me, removed the blinking/flashing issue. 

Note for Compiz Users:
In order for window minimizing and maximizing to work correctly under Compiz, the Focus Prevention Level setting must be set to off in CompizConfig Settings Manager (General Options, Focus and Raise Behaviour)

Minimize on click still does not work but I can wait until the latest is pushed to 17.04 now that I can get software updater to reveal itself without pinning/closing/opening it.

Appreciate the great tool overall. This last release brought me back from antiquated Docky; love that mate-dock includes email counts by default (thunderbird AND evolution).
